### ISSUE TITLE
Error: Cannot find module 'minimist'

### ISSUE THREAD

**Issue by Rolzzz** [gro-ove/ac-server-wrapper#2]
Hello there,

I'm trying to get this to work in CentOS7 linux but I get the following error

[ac@rsc1 ac3Fun]$ ../ac-server-wrapper-master/ac-server-wrapper.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/games/ac-server-wrapper-master/ac-server-wrapper.js:8:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by gro-ove** [comment]
Just use `npm install` in `../ac-server-wrapper-master` after cloning/pulling, it will automatically install and update if needed all used modules (defined in `package.json`).
